language: node_js
notifications:
  email: false
node_js: 14
jobs:
  include:
  - name: Syntax Tests
    script:
    - npm run test-syntax

  - name: Typing Tests
    script:
    - npm run test-typings

  - name: Unit Tests
    if: branch != master
    script:
    - npm run test

  - name: Unit Tests with Coverage
    if: branch = master
    script:
    - npm run test
    after_success:
    - npm run send-coverage
    
  - name: UI Tests
    if: branch = master
    script:
    - npm run test-ui
